        //정답 데이터 
        let answerArray=[
            //0번째 요소에 인물들 정보 배열음 담기
            [
                {
                    "name":"봉준호", 
                    "image":"bongjunho.jpg"
                },
                {
                    "name":"홍진경", 
                    "image":"hongjinkyung.png"
                },
                {
                    "name":"조세호", 
                    "image":"josaeho.jpg"
                },
                {
                    "name":"김연아", 
                    "image":"kimyuna.jpg"
                },
                {
                    "name":"라미란", 
                    "image":"lameelan.jpg"
                },
                {
                    "name":"이재용", 
                    "image":"leejaeyong.png"
                },
                {
                    "name":"이성경", 
                    "image":"leeseongkyung.jpg"
                },
                {
                    "name":"마동석", 
                    "image":"madongseok.jpg"
                },
                {
                    "name":"나영석", 
                    "image":"nayoungseok.png"
                },
                {
                    "name":"손흥민", 
                    "image":"sonheungmin.jpg"
                }
            ],
            //1번째 요소에 음식 정보 배열음 담기
            //["chickensoup.jpg","coldnoodle.jpg","hamburger.jpg","hotteok.jpg","pancake.jpg","pizza.jpg" ,"potato.jpg","ramen.jpg","sushi.jpg","tteokbokki.jpg"]
            [
                {
                    "name":"삼계탕", 
                    "image":"chickensoup.jpg"
                },
                {
                    "name":"냉모밀", 
                    "image":"coldnoodle.jpg"
                },
                {
                    "name":"햄버거", 
                    "image":"hamburger.jpg"
                },
                {
                    "name":"호떡", 
                    "image":"hotteok.jpg"
                },
                {
                    "name":"팬케이크", 
                    "image":"pancake.jpg"
                },
                {
                    "name":"피자", 
                    "image":"pizza.jpg"
                },
                {
                    "name":"감자튀김", 
                    "image":"potato.jpg"
                },
                {
                    "name":"라멘", 
                    "image":"ramen.jpg"
                },
                {
                    "name":"초밥", 
                    "image":"sushi.jpg"
                },
                {
                    "name":"떡볶이", 
                    "image":"tteokbokki.jpg"
                }
            ]

        ];
